# LLM Evaluation Configuration

# Weights & Biases settings
wandb_project: "llm-evaluator"
wandb_entity: "mark-stent-allwyn"  # Optional: specify your W&B entity

# Evaluation settings
max_concurrent: 5          # Maximum concurrent API calls
max_tokens: 1000          # Maximum tokens per response
temperature: 0.7          # Temperature for generation

# Model configurations
models:
  openai:
    - name: "gpt-4o-mini"
      api_key: "${OPENAI_API_KEY}"
    - name: "gpt-3.5-turbo"
      api_key: "${OPENAI_API_KEY}"
    - name: "gpt-4o"
      api_key: "${OPENAI_API_KEY}"
    # Note: o3 is not yet available via API
    # - name: "o3"
    #   api_key: "${OPENAI_API_KEY}"

  anthropic:
    - name: "claude-3-haiku-20240307"
      api_key: "${ANTHROPIC_API_KEY}"
    - name: "claude-3-5-sonnet-20241022"
      api_key: "${ANTHROPIC_API_KEY}"
    # Note: Claude 4 models are not yet available
    # - name: "claude-opus-4-20250514"
    #   api_key: "${ANTHROPIC_API_KEY}"
    # - name: "claude-sonnet-4-20250514"
    #   api_key: "${ANTHROPIC_API_KEY}"

  gemini:
    - name: "gemini-1.5-flash"
      api_key: "${GOOGLE_API_KEY}"
    - name: "gemini-1.5-pro"
      api_key: "${GOOGLE_API_KEY}"
  
  ollama:
    - name: "gemma3:27b"
      base_url: "http://localhost:11434"
    - name: "deepseek-r1"
      base_url: "http://localhost:11434"
    - name: "llama3.2"
      base_url: "http://localhost:11434"

# Pricing configuration (per 1 MILLION tokens, USD)
pricing:
  openai:
    # GPT-4o Models (Latest pricing)
    gpt-4o:
      input: 3.00      # $3.00 per million tokens
      output: 10.00    # $10.00 per million tokens
    gpt-4o-mini:
      input: 0.15      # $0.15 per million tokens  
      output: 0.60     # $0.60 per million tokens
    gpt-4o-2024-08-06:
      input: 3.00
      output: 10.00
    gpt-4o-mini-2024-07-18:
      input: 0.15
      output: 0.60
    
    # O3 Models (Latest reasoning models)
    o3:
      input: 3.00      # $3.00 per million tokens (estimate)
      output: 10.00    # $10.00 per million tokens (estimate)
    
    # GPT-4 Models
    gpt-4:
      input: 30.00     # $30.00 per million tokens
      output: 60.00    # $60.00 per million tokens
    gpt-4-turbo:
      input: 10.00     # $10.00 per million tokens
      output: 30.00    # $30.00 per million tokens
    gpt-4-turbo-2024-04-09:
      input: 10.00
      output: 30.00
    
    # GPT-3.5 Models
    gpt-3.5-turbo:
      input: 1.50      # $1.50 per million tokens
      output: 2.00     # $2.00 per million tokens
    gpt-3.5-turbo-16k:
      input: 3.00
      output: 4.00
    gpt-3.5-turbo-instruct:
      input: 1.50
      output: 2.00
  
  anthropic:
    # Claude 4 Models (Latest - Jan 2025)
    claude-opus-4:
      input: 15.00     # $15.00 per million tokens
      output: 75.00    # $75.00 per million tokens
    claude-opus-4-20250514:
      input: 15.00     # $15.00 per million tokens
      output: 75.00    # $75.00 per million tokens
    claude-sonnet-4:
      input: 3.00      # $3.00 per million tokens
      output: 15.00    # $15.00 per million tokens
    claude-sonnet-4-20250514:
      input: 3.00      # $3.00 per million tokens
      output: 15.00    # $15.00 per million tokens
    
    # Claude 3.5 Models
    claude-3-5-sonnet-20241022:
      input: 3.00      # $3.00 per million tokens
      output: 15.00    # $15.00 per million tokens
    claude-3-5-haiku-20241022:
      input: 1.00      # $1.00 per million tokens
      output: 5.00     # $5.00 per million tokens
    
    # Claude 3 Models
    claude-3-opus-20240229:
      input: 15.00     # $15.00 per million tokens
      output: 75.00    # $75.00 per million tokens
    claude-3-sonnet-20240229:
      input: 3.00      # $3.00 per million tokens
      output: 15.00    # $15.00 per million tokens
    claude-3-haiku-20240307:
      input: 0.25      # $0.25 per million tokens
      output: 1.25     # $1.25 per million tokens
  
  gemini:
    # Gemini 2.0 Models (Latest)
    gemini-2.0-flash:
      input: 0.00      # Free during experimental phase
      output: 0.00
    
    # Gemini 1.5 Models (Current pricing)
    gemini-1.5-pro:
      input: 1.25      # $1.25 per million tokens (up to 128k)
      output: 5.00     # $5.00 per million tokens
    gemini-1.5-flash:
      input: 0.075     # $0.075 per million tokens (up to 128k)
      output: 0.30     # $0.30 per million tokens
    gemini-1.5-flash-exp-0827:
      input: 0.075
      output: 0.30
    
    # Gemini 1.0 Models
    gemini-1.0-pro:
      input: 0.50      # $0.50 per million tokens
      output: 1.50     # $1.50 per million tokens
    gemini-pro:
      input: 0.50
      output: 1.50
    gemini-pro-vision:
      input: 0.50
      output: 1.50
  
  ollama:
    # All Ollama models are free (local inference)
    default:
      input: 0.0
      output: 0.0

# Default pricing for unknown models (per million tokens)
default_pricing:
  input: 1.00    # $1.00 per million tokens
  output: 3.00   # $3.00 per million tokens

# Evaluation metrics to calculate
metrics:
  - "bleu"
  - "rouge"
  - "bert_score"
  - "semantic_similarity"
  - "length_ratio"

# Test case categories to evaluate (optional filter)
categories:
  - "math"
  - "reasoning"
  - "creative"
  - "factual"
  - "coding"